USE [AdventureWorks2019]

GO

CREATE NONCLUSTERED INDEX [IX_Corso04] ON [Production].[Product]
(
	[SellStartDate] ASC,
	[SellEndDate] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)

GO


